name = "p2000nl-test"
main = "worker.js"
compatibility_date = "2024-09-03"

kv_namespaces = [
  { binding = "CONFIG", id = "a57dd40a697742e680fe87be21557b23", preview_id = "a57dd40a697742e680fe87be21557b23" }
]

[env.test]
vars = { POST_NAAM = "test", POST_SLEUTEL = "test", FEED_URL = "https://112-nu.nl/brandweer/rss" }
